---
output: 
  - dynbenchmark::github_markdown_nested
---

```{r setup, include=FALSE}
library(tidyverse)
library(dynbenchmark)

experiment("11-example_predictions")
```

# Examples trajectories

Some examples of inferred trajectories on the same dataset for different methods (`r ref("fig", "example_predictions")`).


```{r}
add_fig(
  fig_path = result_file("example_predictions.pdf", experiment_id = "11-example_predictions"),
  ref_id = "example_predictions", 
  caption_main = "Demonstration of how a common framework for TI methods facilitates broad applicability using some example datasets.", 
  caption_text = glue::glue("Trajectories inferred by each method were projected to a common dimensionality reduction using multi-dimensional scaling. For each dataset, we also calculated a \"consensus\" prediction, by calculating the {label_metric('correlation')} between each pair of models, and picking the model with the highest score on average. (a) The top methods applied on a dataset containing a linear trajectory of differentiation dendritic cells, going from MDP, CDP to PreDC. (b) The top methods applied on a dataset containing a bifurcating trajectory of reprogrammed fibroblasts. (c) A synthetic dataset generated by dyntoy, containing four disconnected trajectories. (d) A synthetic dataset generated by dyngen, containing a cyclic trajectory."),
  width = 14,
  height = 8
)
```
